if has('win32') || has('win64')
    call plug#begin($LOCALAPPDATA . '\vim\plugged')
else
    call plug#begin('~/.local/share/vim/plugged')
endif

Plug 'christoomey/vim-tmux-navigator'
Plug 'edkolev/tmuxline.vim'
Plug 'embear/vim-localvimrc'
Plug 'godlygeek/tabular'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all --xdg' }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vim-python/python-syntax'

" colorschemes
Plug 'chriskempson/base16-vim'
Plug 'frankier/neovim-colors-solarized-truecolor-only'
Plug 'morhetz/gruvbox'
Plug 'nanotech/jellybeans.vim'
Plug 'tomasr/molokai'
Plug 'vim-airline/vim-airline-themes'
Plug 'w0ng/vim-hybrid'

call plug#end()

filetype plugin indent on
syntax enable

set hidden
set virtualedit=block
set wildmenu
set wildmode=longest:full,full
set nowrap
set nostartofline
set ruler
set history=10000
set showcmd
set mouse=a
set mousemodel=popup
set backspace=indent,eol,start
set formatprg=par
set visualbell t_vb=

set hlsearch
set ignorecase
set incsearch
set smartcase

set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

set nofoldenable
set foldmethod=syntax
set foldopen-=block

set undofile
set nobackup

set laststatus=2
set ttimeoutlen=10
set noshowmode
let g:airline_extensions = ['branch', 'tabline']
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#tabline#show_tab_type = 0

let g:tmuxline_powerline_separators = 0
let g:tmuxline_preset = {
      \'a'       : '#S',
      \'win'     : ['#I', '#W'],
      \'cwin'    : ['#I', '#W'],
      \'z'       : '#H',
      \'options' : {'status-justify' : 'left'}}

if has('win32') || has('win64')
    colorscheme default
    let swap_dir = $LOCALAPPDATA . '\vim\swap'
    let &undodir = $LOCALAPPDATA . '\vim\undo'
    let &viminfofile = $LOCALAPPDATA . '\vim\viminfo'
else
    set background=dark
    colorscheme base16-tomorrow-night
    let swap_dir = $HOME . '/.local/share/vim/swap'
    set undodir=~/.local/share/vim/undo
    set viminfofile=~/.local/share/vim/viminfo
endif

let &directory = swap_dir . '//,' . &directory
call mkdir(swap_dir, 'p')
call mkdir(&undodir, 'p')

let mapleader = "\<Space>"
noremap <Space> <Nop>
nnoremap <silent> <Leader>b :Buffers<CR>
nnoremap <silent> <Leader>f :Files<CR>
nnoremap <silent> <Leader>n :nohlsearch<CR>
nnoremap <silent> <Leader>t :Tags<CR>
nnoremap <silent> <Leader>w :update<CR>

nmap Y y$
nmap <C-p> :bp<CR>
nmap <C-n> :bn<CR>

" :help last-position-jump
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

let c_space_errors = 1
let g:python_highlight_all = 1

autocmd BufRead,BufNewFile *.vx setfiletype verilog
autocmd BufRead,BufNewFile gitconfig setfiletype gitconfig
autocmd FileType arduino,c,cpp,cs,cuda setlocal commentstring=//%s
autocmd FileType c,cpp,python setlocal foldmethod=indent
autocmd FileType gitconfig,java setlocal noexpandtab

if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif
