set -g mode-keys vi
set -g status-keys vi
set -g prompt-cursor-style bar
set -g prompt-command-cursor-style block
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle \; \
  if -F '#{==:#{selection_present},0}' 'send -X begin-selection'
bind -T copy-mode-vi y send -X copy-pipe-and-cancel
bind -T copy-mode-vi Y send -X copy-pipe-end-of-line-and-cancel
bind -T copy-mode-vi [ send -X previous-prompt
bind -T copy-mode-vi ] send -X next-prompt
bind -n M-j previous-window
bind -n M-k next-window
bind -n M-Left swap-window -d -s +0 -t -1
bind -n M-Right swap-window -d -s +0 -t +1

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind R source-file ~/.config/tmux/tmux.conf \; display "source-file done"

set -g set-titles on
set -g set-titles-string 'tmux'
if '[ -n "$SSH_CLIENT" ]' "set -ga set-titles-string ' [#H]'"
set -g mouse on
set -g history-limit 50000
set -g focus-events on
set -g renumber-windows on
set -g allow-rename on
set -g aggressive-resize on
set -gu update-environment
set -ga update-environment ' DBUS_SESSION_BUS_ADDRESS'
set -s set-clipboard on

set -g default-terminal 'tmux-direct'
set -su terminal-features
set -sa terminal-features ',xterm-ghostty:256:extkeys:hyperlinks:margins:mouse:osc7:overline:strikethrough:sync:usstyle'
set -sa terminal-features ',vte*:usstyle'

set -ogq @catppuccin_flavor 'mocha'
source ~/.config/tmux/tmux-catppuccin.conf

set-hook -g client-dark-theme {
  set -g @catppuccin_flavor 'mocha'
  source ~/.config/tmux/tmux-catppuccin.conf
}
set-hook -g client-light-theme {
  set -g @catppuccin_flavor 'latte'
  source ~/.config/tmux/tmux-catppuccin.conf
}

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
bind C-\\ send C-\\ # create alternate way to C-\ since vim-tmux-navigator maps it

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'
set -g @resurrect-dir '~/.local/share/tmux/resurrect'

source -q ~/.config/tmux/tmuxlocal.conf

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run ~/.local/share/tmux/plugins/tpm/tpm
